"use strict";
const VERSION="8.0.0", KEY="javiTrailerHelperDataV8";
const FIELDS=[["door","Door"],["camera","Camera"],["atis","ATIS"],["regulator","Regulator"],["tank","Air Tank"],["lfo","LFO"],["lfi","LFI"],["rfi","RFI"],["rfo","RFO"],["lro","LRO"],["lri","LRI"],["rri","RRI"],["rro","RRO"]];
const SERVICES=[
["lfi","LFI",15],["lfo","LFO",15],["lri","LRI",15],["lro","LRO",15],["rfi","RFI",15],["rfo","RFO",15],["rri","RRI",15],["rro","RRO",15],
["tpmsReceiver","TPMS Receiver",60],["atis","ATIS",30],["regulator","Regulator",30],["lampCheck","Lamp Check",30],["cargoCamera","Cargo Camera",30],["cargoSensor","Cargo Sensor",30],["tank","Air Tank Sensor",15],["door","Door Sensor",30],["smart7","Smart7",90],["stealthNet","StealthNet",90]
];
const $=id=>document.getElementById(id); let toastTimer;
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()}
function load(){for(const k of [KEY,"javiTrailerHelperDataV7","javiTrailerHelperDataV6","javiTrailerHelperDataV5","javiTrailerHelperDataV4"]){try{const old=JSON.parse(localStorage.getItem(k));if(old){return{trailers:(old.trailers||[]).map(migrateTrailer),work:(old.work||[]).map(migrateWork)}}}catch{}}return{trailers:[],work:[]}}
function migrateTrailer(t){const s=t.sensors||{};return{id:t.id||uid(),number:(t.number||"").toUpperCase(),vin6:(t.vinLast6||t.vin6||"").slice(-6).toUpperCase(),imei:t.imei||"",status:t.status||"open",createdAt:t.createdAt||Date.now(),updatedAt:t.updatedAt||Date.now(),completedAt:t.completedAt||null,services:Array.isArray(t.services)?t.services:[],totalMinutes:Number(t.totalMinutes)||0,sensors:Object.fromEntries(FIELDS.map(([k])=>[k,s[k]||""]))}}
function migrateWork(w){return{id:w.id||uid(),number:(w.number||"").toUpperCase(),sensors:Array.isArray(w.sensors)?w.sensors:[],completed:!!w.completed,createdAt:w.createdAt||Date.now()}}
let state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(s){clearTimeout(toastTimer);$("toast").textContent=s;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),1500)}
async function copy(v,label){if(!v)return toast("Field is blank");try{await navigator.clipboard.writeText(v)}catch{}toast(label+" copied")}
function formatMinutes(m){m=Number(m)||0;if(m<60)return m+" mins";const h=Math.floor(m/60),r=m%60;return h+" hour"+(h!==1?"s":"")+(r?" "+r+" mins":"")}
function fieldHtml(label,value){if(!value)return "";return `<button class="copyField" data-copy="${esc(value)}" data-label="${label}"><span><span class="fieldName">${label}</span><span class="fieldValue">${esc(value)}</span></span><span class="copyHint">Tap to copy</span></button>`}
function completionHtml(t){if(t.status!=="completed")return "";const names=t.services.map(id=>serviceLabel(id)).filter(Boolean);return `<div class="completionSummary"><div><b>Completed</b>${t.completedAt?`<small>${new Date(t.completedAt).toLocaleString()}</small>`:""}</div><strong>${formatMinutes(t.totalMinutes)}</strong>${names.length?`<p>${names.map(esc).join(" · ")}</p>`:""}</div>`}
function render(){const q=$("search").value.trim().toUpperCase();const trailers=[...state.trailers].filter(t=>!q||t.number.includes(q)||t.vin6.includes(q)).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$("trailerList").innerHTML=trailers.map(t=>`<article class="trailerCard"><div class="trailerTop"><div><button class="titleCopy" data-copy="${esc(t.number)}" data-label="Trailer">${esc(t.number)}</button><p class="meta">VIN ${esc(t.vin6||"")}</p></div><span class="badge ${t.status}">${t.status==="completed"?"Completed":"Open"}</span></div>${fieldHtml("VIN",t.vin6)}${fieldHtml("IMEI",t.imei)}${FIELDS.map(([k,l])=>fieldHtml(l,t.sensors[k])).join("")}${completionHtml(t)}<div class="cardActions"><button class="secondary" data-edit="${t.id}">Edit Info</button><button class="primary" data-complete="${t.id}">${t.status==="completed"?"Edit Completion":"Complete Trailer"}</button></div></article>`).join("");$("noTrailers").classList.toggle("hidden",trailers.length>0);
const work=[...state.work].sort((a,b)=>Number(a.completed)-Number(b.completed)||(b.createdAt||0)-(a.createdAt||0));$("workList").innerHTML=work.map(w=>`<article class="workCard"><div class="workTop"><h2>${esc(w.number)}</h2><button class="${w.completed?"secondary":"primary"}" data-toggle="${w.id}">${w.completed?"Undo":"Complete"}</button></div><div class="workSensors">${w.sensors.map(k=>`<span class="sensorChip">${esc(labelFor(k))}</span>`).join("")||'<span class="hint">No repairs selected</span>'}</div><details><summary>Add another sensor</summary><div class="otherGrid">${FIELDS.filter(([k])=>!w.sensors.includes(k)).map(([k,l])=>`<button class="secondary" data-addsensor="${w.id}" data-sensor="${k}">${l}</button>`).join("")}</div></details><button class="danger" data-remove="${w.id}">Remove</button></article>`).join("");$("noWork").classList.toggle("hidden",work.length>0);
$("totalCount").textContent=state.trailers.length;$("doneCount").textContent=state.trailers.filter(t=>t.status==="completed").length;$("openCount").textContent=state.trailers.filter(t=>t.status!=="completed").length}
function labelFor(k){return (FIELDS.find(x=>x[0]===k)||[k,k])[1]}
function serviceLabel(id){return (SERVICES.find(x=>x[0]===id)||[])[1]||""}
function setup(){$("sensorInputs").innerHTML=FIELDS.map(([k,l])=>`<label>${l}<input id="s_${k}" autocapitalize="characters"></label>`).join("");$("workSensorPicker").innerHTML=FIELDS.map(([k,l])=>`<label class="checkItem"><input type="checkbox" value="${k}">${l}</label>`).join("");$("servicePicker").innerHTML=SERVICES.map(([id,label,mins])=>`<label class="serviceItem"><input type="checkbox" value="${id}" data-mins="${mins}"><span><b>${label}</b><small>${formatMinutes(mins)}</small></span></label>`).join("")}
function openDialog(id){const t=state.trailers.find(x=>x.id===id)||migrateTrailer({id:uid(),createdAt:Date.now()});$("dialogTitle").textContent=id?"Edit Trailer":"Add Trailer";$("editId").value=id||"";$("trailerId").value=t.number;$("vin6").value=t.vin6;$("imei").value=t.imei;FIELDS.forEach(([k])=>$("s_"+k).value=t.sensors[k]||"");$("pasteData").value="";$("deleteTrailer").classList.toggle("hidden",!id);$("trailerDialog").showModal()}
function parsePaste(raw){const out={sensors:{}};const lines=raw.replace(/\r/g,"").split("\n");let first=lines.find(x=>x.trim()&&!x.includes(":"));if(first)out.number=first.trim().toUpperCase();for(const line of lines){const m=line.match(/^\s*([^:]+):\s*(.*)$/);if(!m)continue;const l=m[1].trim().toUpperCase(),v=m[2].trim();if(l==="VIN")out.vin6=v.slice(-6).toUpperCase();else if(l==="IMEI")out.imei=v;else{const map={"DOOR":"door","CAMERA":"camera","ATIS":"atis","REGULATOR":"regulator","AIR TANK":"tank","TANK":"tank","LFO":"lfo","LFI":"lfi","RFI":"rfi","RFO":"rfo","LRO":"lro","LRI":"lri","RRI":"rri","RRO":"rro"};if(map[l])out.sensors[map[l]]=v}}return out}
function recommendedServices(t){const ids=[];for(const [k] of FIELDS){if(!t.sensors[k])continue;if(k==="camera")ids.push("cargoCamera");else ids.push(k)}const w=state.work.find(x=>x.number===t.number&&!x.completed);if(w)for(const k of w.sensors){const id=k==="camera"?"cargoCamera":k;if(SERVICES.some(s=>s[0]===id)&&!ids.includes(id))ids.push(id)}return ids}
function openComplete(id){const t=state.trailers.find(x=>x.id===id);if(!t)return;$("completeId").value=id;$("completeTrailerNumber").textContent=t.number;const selected=t.services.length?t.services:recommendedServices(t);$("servicePicker").querySelectorAll("input").forEach(x=>x.checked=selected.includes(x.value));$("reopenTrailer").classList.toggle("hidden",t.status!=="completed");updateTime();$("completeDialog").showModal()}
function updateTime(){const total=[...$("servicePicker").querySelectorAll("input:checked")].reduce((n,x)=>n+Number(x.dataset.mins),0);$("timeTotal").textContent=formatMinutes(total)}
$("autoFill").onclick=()=>{const d=parsePaste($("pasteData").value);if(d.number)$("trailerId").value=d.number;if(d.vin6)$("vin6").value=d.vin6;if(d.imei)$("imei").value=d.imei;FIELDS.forEach(([k])=>{if(d.sensors[k]!==undefined)$("s_"+k).value=d.sensors[k]});toast("Fields filled")};
$("trailerForm").onsubmit=e=>{e.preventDefault();const number=$("trailerId").value.trim().toUpperCase();if(!number)return;const id=$("editId").value||uid();const old=state.trailers.find(t=>t.id===id);const t={id,number,vin6:$("vin6").value.trim().slice(-6).toUpperCase(),imei:$("imei").value.trim(),status:old?.status||"open",createdAt:old?.createdAt||Date.now(),updatedAt:Date.now(),completedAt:old?.completedAt||null,services:old?.services||[],totalMinutes:old?.totalMinutes||0,sensors:Object.fromEntries(FIELDS.map(([k])=>[k,$("s_"+k).value.trim()]))};const i=state.trailers.findIndex(x=>x.id===id);if(i>=0)state.trailers[i]=t;else state.trailers.unshift(t);$("trailerDialog").close();save();toast("Trailer saved")};
$("completeForm").onsubmit=e=>{e.preventDefault();const t=state.trailers.find(x=>x.id===$("completeId").value);if(!t)return;const checked=[...$("servicePicker").querySelectorAll("input:checked")];t.services=checked.map(x=>x.value);t.totalMinutes=checked.reduce((n,x)=>n+Number(x.dataset.mins),0);t.status="completed";t.completedAt=Date.now();t.updatedAt=Date.now();const w=state.work.find(x=>x.number===t.number&&!x.completed);if(w)w.completed=true;$("completeDialog").close();save();toast("Trailer completed")};
$("reopenTrailer").onclick=()=>{const t=state.trailers.find(x=>x.id===$("completeId").value);if(!t)return;t.status="open";t.completedAt=null;$("completeDialog").close();save();toast("Trailer marked open")};
$("servicePicker").onchange=updateTime;
$("addWork").onclick=()=>{const number=$("workTrailer").value.trim().toUpperCase();if(!number)return toast("Enter trailer number");const sensors=[...$("workSensorPicker").querySelectorAll("input:checked")].map(x=>x.value);state.work.unshift({id:uid(),number,sensors,completed:false,createdAt:Date.now()});$("workTrailer").value="";$("workSensorPicker").querySelectorAll("input").forEach(x=>x.checked=false);save()};
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.edit)openDialog(b.dataset.edit);if(b.dataset.complete)openComplete(b.dataset.complete);if(b.dataset.copy!==undefined)copy(b.dataset.copy,b.dataset.label);if(b.dataset.toggle){const w=state.work.find(x=>x.id===b.dataset.toggle);w.completed=!w.completed;save()}if(b.dataset.remove){state.work=state.work.filter(x=>x.id!==b.dataset.remove);save()}if(b.dataset.addsensor){const w=state.work.find(x=>x.id===b.dataset.addsensor);if(!w.sensors.includes(b.dataset.sensor))w.sensors.push(b.dataset.sensor);save()}});
$("copyNA").onclick=()=>copy("NA","NA");
$("deleteTrailer").onclick=()=>{const id=$("editId").value;if(confirm("Delete this trailer?")){state.trailers=state.trailers.filter(t=>t.id!==id);$("trailerDialog").close();save()}};
$("addTrailer").onclick=()=>openDialog();$("closeDialog").onclick=()=>$("trailerDialog").close();$("closeComplete").onclick=()=>$("completeDialog").close();$("search").oninput=render;document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.view).classList.add("active")});
setup();render();if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js");
