"use strict";
const APP_VERSION=6, DATA_KEY="javiTrailerHelperDataV6", AI_URL_KEY="javiTrailerHelperAiUrl";
const SENSOR_FIELDS=[["nosebox","Nosebox"],["atis","ATIS"],["receiver","TPMS Receiver"],["camera","Camera"],["door","Door"],["tank","Tank"],["regulator","Regulator"],["lfo","LFO"],["lfi","LFI"],["rfi","RFI"],["rfo","RFO"],["lro","LRO"],["lri","LRI"],["rri","RRI"],["rro","RRO"],["cargo","Cargo Plate"]];
const SCAN_FIELDS=[["number","Trailer number"],["vin","Full VIN"],["vinLast6","Last 6 VIN"],["imei","IMEI"],["iccid","ICCID"],["mac","MAC address"],["caseNumber","Case number"],...SENSOR_FIELDS];
const $=id=>document.getElementById(id); let toastTimer,scanFiles=[],scanData={};
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function blankTrailer(){return{id:uid(),number:"",vin:"",vinLast6:"",imei:"",iccid:"",mac:"",caseNumber:"",notes:"",sensors:Object.fromEntries(SENSOR_FIELDS.map(([k])=>[k,""]))}}
let state=loadState(), scanCancelled=false, activeWorker=null;
function loadState(){for(const key of [DATA_KEY,"javiTrailerHelperDataV5","javiTrailerHelperDataV4","javiTrailerHelperDataV3","javiTrailerHelperDataV2"]){try{const d=JSON.parse(localStorage.getItem(key));if(d&&Array.isArray(d.trailers)&&Array.isArray(d.work)){return{version:APP_VERSION,trailers:d.trailers,work:d.work}}}catch{}}return{version:APP_VERSION,trailers:[],work:[]}}
function saveState(){localStorage.setItem(DATA_KEY,JSON.stringify(state));renderAll()}
function esc(v=""){return String(v).replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function norm(v=""){return v.trim().toUpperCase().replace(/\s+/g,"")}
function today(){return new Date().toLocaleDateString("en-CA")}
function toast(m){clearTimeout(toastTimer);$("toast").textContent=m;$("toast").classList.add("show");toastTimer=setTimeout(()=>$("toast").classList.remove("show"),1800)}
async function copyText(t,l="Value"){if(!t)return toast(`No ${l.toLowerCase()} saved`);try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement("textarea");a.value=t;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}toast(`${l} copied`)}
function renderAll(){renderTrailers();renderWork();const d=today();$("trailerCount").textContent=state.trailers.length;$("todayCount").textContent=state.work.filter(x=>x.completed&&x.completedDate===d).length;$("openCount").textContent=state.work.filter(x=>!x.completed).length}
function renderTrailers(){const q=$("searchInput").value.trim().toUpperCase();const a=state.trailers.filter(t=>!q||t.number.includes(q)||(t.vinLast6||"").includes(q)).sort((x,y)=>x.number.localeCompare(y.number));$("trailerList").innerHTML=a.map(t=>{const f=[["VIN",t.vin||t.vinLast6],["Last 6",t.vinLast6],["IMEI",t.imei],["ICCID",t.iccid],["MAC",t.mac],["Case",t.caseNumber],...SENSOR_FIELDS.map(([k,l])=>[l,t.sensors?.[k]])].filter(x=>x[1]);return`<article class="trailer-card"><div class="trailer-head"><div><h2 class="trailer-title">${esc(t.number)}</h2><p class="meta">${t.vinLast6?`VIN ${esc(t.vinLast6)}`:"No VIN saved"}</p></div><div class="trailer-actions"><button class="secondary mini" data-add-work="${t.id}">Today</button><button class="secondary mini" data-edit="${t.id}">Edit</button></div></div>${f.length?`<div class="sensor-grid">${f.map(([l,v])=>`<button class="copy-field" data-copy="${esc(v)}" data-label="${esc(l)}"><small>${esc(l)}</small><span>${esc(v)}</span></button>`).join("")}</div>`:`<p class="hint">Tap Edit to add information.</p>`}${t.notes?`<p class="work-repairs">${esc(t.notes)}</p>`:""}</article>`}).join("");$("emptyTrailers").classList.toggle("hidden",a.length>0)}
function renderWork(){const a=[...state.work].sort((x,y)=>Number(x.completed)-Number(y.completed)||x.number.localeCompare(y.number));$("workList").innerHTML=a.map(x=>`<article class="work-card ${x.completed?"done":""}"><div class="work-head"><div><div class="work-name">${esc(x.number)}</div>${x.repairs?`<p class="work-repairs">${esc(x.repairs)}</p>`:""}</div><button class="${x.completed?"secondary":"primary"} mini" data-toggle-work="${x.id}">${x.completed?"Undo":"Complete"}</button></div><div class="button-row"><button class="secondary mini" data-edit-work="${x.id}">Repairs</button><button class="danger mini" data-delete-work="${x.id}">Remove</button></div></article>`).join("");$("emptyWork").classList.toggle("hidden",a.length>0)}
function setupFields(){$("sensorInputs").innerHTML=SENSOR_FIELDS.map(([k,l])=>`<label>${l}<input id="sensor_${k}" autocapitalize="characters"></label>`).join("");$("noteComponent").innerHTML=SENSOR_FIELDS.filter(x=>x[0]!=="cargo").map(([,l])=>`<option>${l}</option>`).join("");$("scanResults").innerHTML=SCAN_FIELDS.map(([k,l])=>`<label>${l}<input id="scan_${k}" autocapitalize="characters"></label>`).join("")}

const PASTE_ALIASES={
  number:["TRAILER","TRAILER NUMBER","TRAILER #","UNIT","UNIT NUMBER"],
  vin:["VIN","FULL VIN","VIN NUMBER"],
  vinLast6:["LAST 6","LAST 6 VIN","VIN LAST 6","LAST SIX VIN"],
  imei:["IMEI"],iccid:["ICCID","SIM","SIM ICCID"],mac:["MAC","MAC ADDRESS"],
  caseNumber:["CASE","CASE NUMBER","CASE #","PCT CASE"],
  nosebox:["NOSEBOX","NOSE BOX"],atis:["ATIS"],receiver:["RECEIVER","TPMS RECEIVER"],
  camera:["CAMERA"],door:["DOOR","DOOR SENSOR"],tank:["TANK","TANK SENSOR"],
  regulator:["REGULATOR","REGULATOR SENSOR"],lfo:["LFO"],lfi:["LFI"],rfi:["RFI"],rfo:["RFO"],
  lro:["LRO"],lri:["LRI"],rri:["RRI"],rro:["RRO"],cargo:["CARGO","CARGO PLATE","CARGO SENSOR"],
  notes:["NOTES","NOTE"]
};
function cleanPasteValue(value=""){
  const v=String(value).trim().replace(/^[-–—•]+\s*/,"");
  return /^(N\/?A|NONE|NOT SHOWN|MISSING INFO|UNKNOWN|BLANK|-)?$/i.test(v)?"":v;
}
function findPasteKey(label=""){
  const n=label.toUpperCase().replace(/[^A-Z0-9# ]/g," ").replace(/\s+/g," ").trim();
  for(const [key,aliases] of Object.entries(PASTE_ALIASES))if(aliases.includes(n))return key;
  return "";
}
function parseTrailerPaste(raw=""){
  const result={};
  const lines=String(raw).replace(/\r/g,"").split("\n").map(x=>x.trim()).filter(Boolean);
  let pending="";
  for(const line of lines){
    const pair=line.match(/^([^:=–—]{1,30})\s*(?::|=|–|—)\s*(.+)$/);
    if(pair){const key=findPasteKey(pair[1]);if(key){result[key]=cleanPasteValue(pair[2]);pending="";continue}}
    const onlyKey=findPasteKey(line.replace(/:$/,""));
    if(onlyKey){pending=onlyKey;continue}
    if(pending){result[pending]=cleanPasteValue(line);pending="";continue}
    const vin=cleanVin(line);if(validVin(vin)&&!result.vin){result.vin=vin;continue}
    const trailer=(line.toUpperCase().match(/\b(?:HV|GV|WV|DV|SV|V)\d{5,8}\b/)||[])[0];if(trailer&&!result.number)result.number=trailer;
  }
  if(result.vin){result.vin=cleanVin(result.vin);if(validVin(result.vin))result.vinLast6=result.vin.slice(-6)}
  if(result.number)result.number=norm(result.number);
  if(result.mac){const m=result.mac.toUpperCase().replace(/[^A-F0-9]/g,"");result.mac=m.length===12?m.match(/.{2}/g).join(":"):result.mac.toUpperCase()}
  return result;
}
function autoFillTrailerFromPaste(){
  const raw=$("trailerPaste").value.trim();if(!raw)return toast("Paste trailer information first");
  const data=parseTrailerPaste(raw);let count=0;
  const ids={number:"trailerNumber",vin:"vin",vinLast6:"vinLast6",imei:"imei",iccid:"iccid",mac:"mac",caseNumber:"caseNumber",notes:"trailerNotes"};
  for(const [key,id] of Object.entries(ids)){if(data[key]){$(id).value=data[key];count++}}
  for(const [key] of SENSOR_FIELDS){if(data[key]){$("sensor_"+key).value=data[key];count++}}
  if($("vin").value&&!$("vinLast6").value)$("vinLast6").value=cleanVin($("vin").value).slice(-6);
  $("pasteStatus").textContent=count?`${count} field${count===1?"":"s"} filled. Review them, then tap Save Trailer.`:"No labeled trailer fields were found.";
  toast(count?`${count} fields filled`:"Nothing recognized");
}

function openTrailer(id=""){const t=state.trailers.find(x=>x.id===id)||blankTrailer();$("dialogTitle").textContent=id?"Edit Trailer":"Add Trailer";$("editId").value=id;for(const k of ["number","vin","vinLast6","imei","iccid","mac","caseNumber","notes"]){const el=$(k==="number"?"trailerNumber":k==="notes"?"trailerNotes":k);el.value=t[k]||""}SENSOR_FIELDS.forEach(([k])=>$("sensor_"+k).value=t.sensors?.[k]||"");$("trailerPaste").value="";$("pasteStatus").textContent="";$("deleteTrailerButton").classList.toggle("hidden",!id);$("trailerDialog").showModal()}
function saveTrailer(e){e.preventDefault();const n=norm($("trailerNumber").value);if(!n)return toast("Trailer number is required");const id=$("editId").value||uid();if(state.trailers.some(t=>t.number===n&&t.id!==id))return toast("That trailer already exists");const fullVin=cleanVin($("vin").value);const last6=($("vinLast6").value.trim().toUpperCase()||fullVin.slice(-6)).slice(-6);const t={id,number:n,vin:fullVin,vinLast6:last6,imei:$("imei").value.trim(),iccid:$("iccid").value.trim(),mac:$("mac").value.trim().toUpperCase(),caseNumber:$("caseNumber").value.trim(),notes:$("trailerNotes").value.trim(),sensors:Object.fromEntries(SENSOR_FIELDS.map(([k])=>[k,$("sensor_"+k).value.trim()]))};const i=state.trailers.findIndex(x=>x.id===id);i>=0?state.trailers[i]=t:state.trailers.push(t);$("trailerDialog").close();saveState();toast("Trailer saved")}
function addWork(raw){let c=0;raw.split(/[\n,]+/).map(s=>norm((s.match(/[A-Z]{0,3}\d{3,}/i)||[s.split(/\s+/)[0]])[0])).filter(Boolean).forEach(n=>{if(!state.work.some(x=>x.number===n&&!x.completed)){state.work.push({id:uid(),number:n,repairs:"",completed:false,completedDate:""});c++}});saveState();return c}
function generateNote(){const c=$("noteComponent").value,a=$("noteAction").value,cl=c.toLowerCase();const m={noIssues:`No issues found with ${c}. Triggered the sensor and verified that it was working on the PCT app.`,replaced:`${c} sensor was not working on the PCT app. Replaced it with a new sensor and verified that it was working on the PCT app.`,missing:`${c} sensor was missing. Replaced it with a new sensor and verified that it was working on the PCT app.`,repairedApp:`Repaired the ${cl} sensor on the PCT app and verified that it was working on the PCT app.`,rewired:`Rewired the ${cl} sensor and verified that it was working on the PCT app.`,verified:`Performed a health check on the ${cl} sensor and verified that it was working properly on the PCT app.`,valve:`Regulator valve was turned off. Turned it back on and verified that the regulator sensor was working on the PCT app.`,custom:$("customNote").value.trim()};let n=m[a]||"";if($("smart7Reason").checked&&n)n=n.replace(/\.$/,"")+" after replacing the damaged Smart 7 box.";if($("verifySerial").checked&&n)n=n.replace(/\.$/,"")+" Also verified that the sensor serial number matched.";if($("noteCase").value.trim()&&n)n=`Case ${$("noteCase").value.trim()}: ${n}`;$("generatedNote").value=n}
function exportBackup(){const b=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`javi-trailer-helper-backup-${today()}.json`;a.click();URL.revokeObjectURL(u);toast("Backup exported")}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.trailers)||!Array.isArray(d.work))throw 0;state={version:APP_VERSION,trailers:d.trailers,work:d.work};saveState();$("backupDialog").close();toast("Backup restored")}catch{alert("That file is not a valid backup.")}};r.readAsText(file)}
function previewPhotos(){const box=$("photoPreview");box.innerHTML="";scanFiles=[...$("scanFiles").files];scanFiles.forEach(f=>{const img=document.createElement("img");img.className="photo-thumb";img.src=URL.createObjectURL(f);box.appendChild(img)});$("scanButton").disabled=!scanFiles.length;$("aiScanButton").disabled=!scanFiles.length;$("scanStatus").textContent=scanFiles.length?`${scanFiles.length} photo${scanFiles.length===1?"":"s"} selected.`:""}
async function loadTesseract(){if(window.Tesseract)return;$ ("scanStatus").textContent="Loading photo reader…";await Promise.race([new Promise((res,rej)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js";s.onload=res;s.onerror=()=>rej(new Error("Could not load photo reader"));document.head.appendChild(s)}),new Promise((_,rej)=>setTimeout(()=>rej(new Error("Photo reader timed out while loading")),20000))])}
function firstMatch(text,patterns){for(const p of patterns){const m=text.match(p);if(m)return(m[1]||m[0]).replace(/\s/g,"")}return""}
function cleanVin(v=""){return String(v).toUpperCase().replace(/[^A-Z0-9]/g,"").replace(/[IOQ]/g,c=>({I:"1",O:"0",Q:"0"}[c])).slice(0,17)}
function validVin(v){return /^[A-HJ-NPR-Z0-9]{17}$/.test(v)}
function parseOCR(text){const u=text.toUpperCase(),out={};out.number=norm($("scanTrailerNumber").value)||firstMatch(u,[/\b((?:HV|GV|WV|DV|SV|V)\d{5,8})\b/]);
const candidates=[...u.matchAll(/\b[A-Z0-9][A-Z0-9\s-]{15,24}[A-Z0-9]\b/g)].map(m=>cleanVin(m[0])).filter(validVin);
let vin=candidates.find(v=>!/^(.)\1+$/.test(v))||"";
if(!vin){const near=firstMatch(u,[/(?:VIN|VEHICLE\s+IDENTIFICATION)[^A-Z0-9]{0,18}([A-Z0-9\s-]{17,25})/]);const c=cleanVin(near);if(validVin(c))vin=c}
out.vin=vin;out.vinLast6=vin?vin.slice(-6):firstMatch(u,[/(?:VIN|LAST\s*6)[^A-Z0-9]{0,12}([A-Z0-9]{6})\b/]);out.imei=firstMatch(u,[/(?:IMEI)[^0-9]{0,12}(\d{14,17})\b/,/\b(86\d{13})\b/]);out.iccid=firstMatch(u,[/(?:ICCID|SIM)[^0-9]{0,15}(89\d{17,20})\b/,/\b(89\d{17,20})\b/]);out.mac=firstMatch(u,[/(?:MAC)[^A-F0-9]{0,12}([A-F0-9]{2}(?::|-)?[A-F0-9]{2}(?::|-)?[A-F0-9]{2}(?::|-)?[A-F0-9]{2}(?::|-)?[A-F0-9]{2}(?::|-)?[A-F0-9]{2})\b/]);if(out.mac&&out.mac.length===12)out.mac=out.mac.match(/.{2}/g).join(":");out.caseNumber=firstMatch(u,[/(?:CASE|TICKET)[^0-9]{0,10}(00\d{6})\b/,/\b(00\d{6})\b/]);
const explicit={lfo:/\bLFO\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/,lfi:/\bLFI\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/,rfi:/\bRFI\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/,rfo:/\bRFO\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/,lro:/\bLRO\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/,lri:/\bLRI\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/,rri:/\bRRI\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/,rro:/\bRRO\b[^A-F0-9]{0,14}([A-F0-9]{6,16})\b/};for(const [k,re] of Object.entries(explicit)){const m=u.match(re);if(m)out[k]=m[1]}
return out}
function getAiUrl(){return (localStorage.getItem(AI_URL_KEY)||"").replace(/\/$/,"")}
async function imageToDataUrl(file){const canvas=await prepareImage(file,1280);return canvas.toDataURL("image/jpeg",0.72)}
function normalizeAiResult(d){const out={};for(const [k] of SCAN_FIELDS)out[k]=String(d?.[k]||"").trim();out.vin=cleanVin(out.vin);if(validVin(out.vin))out.vinLast6=out.vin.slice(-6);else out.vin="";out.number=norm(out.number||$("scanTrailerNumber").value);if(out.mac){const m=out.mac.toUpperCase().replace(/[^A-F0-9]/g,"");out.mac=m.length===12?m.match(/.{2}/g).join(":"):out.mac.toUpperCase()}return out}
async function scanPhotosWithAI(){if(!scanFiles.length)return;const base=getAiUrl();if(!base){$("backupDialog").showModal();$("aiSettingsStatus").textContent="Add your AI backend address first.";return}scanCancelled=false;$("scanButton").disabled=true;$("aiScanButton").disabled=true;$("cancelScanButton").classList.remove("hidden");$("scanProgress").classList.remove("hidden");$("scanProgressBar").style.width="5%";$("scanStatus").textContent="Preparing photos for AI…";$("scanLog").innerHTML="";$("scanLog").classList.remove("hidden");try{const images=[];for(let i=0;i<scanFiles.length;i++){if(scanCancelled)throw new Error("Scan cancelled");$("scanStatus").textContent=`Preparing photo ${i+1} of ${scanFiles.length}…`;images.push(await withTimeout(imageToDataUrl(scanFiles[i]),20000,"Photo preparation"));$("scanProgressBar").style.width=`${5+Math.round(((i+1)/scanFiles.length)*35)}%`;addScanLog(`Photo ${i+1}: prepared`,"ok")}("scanStatus").textContent="AI is reading and combining the trailer information…";$("scanProgressBar").style.width="55%";const res=await withTimeout(fetch(base+"/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trailerNumber:norm($("scanTrailerNumber").value),images})}),120000,"AI analysis");const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||`AI request failed (${res.status})`);scanData=normalizeAiResult(body.data||body);SCAN_FIELDS.forEach(([k])=>$("scan_"+k).value=scanData[k]||"");$("scanRawText").value=body.notes||"AI analysis completed.";$("scanResultsCard").classList.remove("hidden");$("scanProgressBar").style.width="100%";$("scanStatus").textContent="AI scan complete. Review every field before saving.";addScanLog("AI results are ready for review.","ok")}catch(e){$("scanStatus").textContent="AI scan did not finish.";addScanLog(e.message,"error")}finally{$("scanButton").disabled=false;$("aiScanButton").disabled=false;$("cancelScanButton").classList.add("hidden")}}
function addScanLog(message,type=""){const box=$("scanLog");box.classList.remove("hidden");const row=document.createElement("div");row.className=type;row.textContent=message;box.appendChild(row);box.scrollTop=box.scrollHeight}
async function prepareImage(file,max=1800){const bitmap=await createImageBitmap(file);scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext("2d",{alpha:false});ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas}
async function withTimeout(promise,ms,label){let timer;try{return await Promise.race([promise,new Promise((_,rej)=>timer=setTimeout(()=>rej(new Error(label+" timed out")),ms))])}finally{clearTimeout(timer)}}
async function scanPhotos(){if(!scanFiles.length)return;scanCancelled=false;$("scanButton").disabled=true;$("cancelScanButton").classList.remove("hidden");$("scanProgress").classList.remove("hidden");$("scanResultsCard").classList.add("hidden");$("scanLog").innerHTML="";$("scanLog").classList.remove("hidden");let all="",completed=0,skipped=0;try{await loadTesseract();activeWorker=await withTimeout(Tesseract.createWorker("eng",1,{logger:m=>{if(m.status==="recognizing text")$("scanProgressBar").style.width=`${Math.min(99,((completed+m.progress)/scanFiles.length)*100)}%`}}),30000,"Photo reader");for(let i=0;i<scanFiles.length;i++){if(scanCancelled)break;$("scanStatus").textContent=`Reading photo ${i+1} of ${scanFiles.length}…`;try{const canvas=await withTimeout(prepareImage(scanFiles[i]),15000,"Image preparation");const result=await withTimeout(activeWorker.recognize(canvas),45000,"Photo "+(i+1));const text=result?.data?.text||"";all+=`\n\n--- PHOTO ${i+1} ---\n${text}`;completed++;addScanLog(`Photo ${i+1}: read successfully`,"ok")}catch(err){skipped++;addScanLog(`Photo ${i+1}: skipped (${err.message})`,"skip")}$("scanProgressBar").style.width=`${((i+1)/scanFiles.length)*100}%`}if(scanCancelled){$("scanStatus").textContent=`Scan cancelled. ${completed} photo${completed===1?"":"s"} read, ${skipped} skipped.`}else{$("scanStatus").textContent=`Scan finished. ${completed} photo${completed===1?"":"s"} read, ${skipped} skipped.`}if(all.trim()){scanData=parseOCR(all);SCAN_FIELDS.forEach(([k])=>$("scan_"+k).value=scanData[k]||"");$("scanRawText").value=all.trim();$("scanResultsCard").classList.remove("hidden");addScanLog("Partial results are ready for review.","ok")}else if(!scanCancelled){throw new Error("No photos could be read")}}catch(e){$("scanStatus").textContent="The photo reader stopped, but the app is still responsive.";addScanLog(e.message,"error")}finally{if(activeWorker){try{await activeWorker.terminate()}catch{}activeWorker=null}$("scanButton").disabled=false;$("cancelScanButton").classList.add("hidden")}}
async function cancelScan(){scanCancelled=true;$("scanStatus").textContent="Cancelling after the current photo…";addScanLog("Cancel requested.","skip");if(activeWorker){try{await activeWorker.terminate()}catch{}activeWorker=null}}
function saveScan(){const n=norm($("scan_number").value);if(!n)return toast("Trailer number is required");let t=state.trailers.find(x=>x.number===n)||blankTrailer();t.number=n;t.vin=cleanVin($("scan_vin").value);t.vinLast6=($("scan_vinLast6").value.trim().toUpperCase()||t.vin.slice(-6)).slice(-6);for(const k of ["imei","iccid","mac","caseNumber"])t[k]=$("scan_"+k).value.trim();SENSOR_FIELDS.forEach(([k])=>t.sensors[k]=$("scan_"+k).value.trim());if(!state.trailers.some(x=>x.id===t.id))state.trailers.push(t);saveState();toast("Trailer saved");document.querySelector('[data-view="trailersView"]').click()}
function clearScan(){$("scanFiles").value="";scanFiles=[];$("photoPreview").innerHTML="";$("scanResultsCard").classList.add("hidden");$("scanStatus").textContent="";$("scanLog").innerHTML="";$("scanLog").classList.add("hidden");$("scanProgress").classList.add("hidden");$("scanProgressBar").style.width="0"}
setupFields();renderAll();
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.matches(".tab")){document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.view).classList.add("active")}if(b.dataset.copy)copyText(b.dataset.copy,b.dataset.label);if(b.dataset.edit)openTrailer(b.dataset.edit);if(b.dataset.addWork){const t=state.trailers.find(x=>x.id===b.dataset.addWork);if(t)addWork(t.number)}if(b.dataset.toggleWork){const x=state.work.find(y=>y.id===b.dataset.toggleWork);x.completed=!x.completed;x.completedDate=x.completed?today():"";saveState()}if(b.dataset.deleteWork){state.work=state.work.filter(x=>x.id!==b.dataset.deleteWork);saveState()}if(b.dataset.editWork){const x=state.work.find(y=>y.id===b.dataset.editWork),v=prompt("Repairs for "+x.number,x.repairs||"");if(v!==null){x.repairs=v.trim();saveState()}}});
$("searchInput").addEventListener("input",renderTrailers);$("addTrailerButton").onclick=()=>openTrailer();$("autoFillTrailerButton").onclick=autoFillTrailerFromPaste;$("clearTrailerPasteButton").onclick=()=>{$("trailerPaste").value="";$("pasteStatus").textContent=""};$("closeDialogButton").onclick=()=>$("trailerDialog").close();$("trailerForm").onsubmit=saveTrailer;$("deleteTrailerButton").onclick=()=>{const id=$("editId").value,t=state.trailers.find(x=>x.id===id);if(t&&confirm(`Delete ${t.number}?`)){state.trailers=state.trailers.filter(x=>x.id!==id);$("trailerDialog").close();saveState()}};
$("addWorkButton").onclick=()=>{const n=addWork($("workPaste").value);$("workPaste").value="";toast(`${n} trailer${n===1?"":"s"} added`)};$("clearCompletedButton").onclick=()=>{state.work=state.work.filter(x=>!x.completed);saveState()};
$("noteAction").onchange=()=>$("customNoteWrap").classList.toggle("hidden",$("noteAction").value!=="custom");$("generateNoteButton").onclick=generateNote;$("copyNoteButton").onclick=()=>copyText($("generatedNote").value,"Note");
$("backupButton").onclick=()=>$("backupDialog").showModal();$("closeBackupButton").onclick=()=>$("backupDialog").close();$("exportButton").onclick=exportBackup;$("importFile").onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$("refreshAppButton").onclick=async()=>{try{if("serviceWorker" in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.update()))}toast("Refreshing app…");setTimeout(()=>location.reload(true),500)}catch{location.reload(true)}};$("resetButton").onclick=()=>{if(confirm("Erase all saved trailer and work-list data?")){state={version:APP_VERSION,trailers:[],work:[]};saveState();$("backupDialog").close()}};
$("scanFiles").onchange=previewPhotos;$("scanButton").onclick=scanPhotos;$("aiScanButton").onclick=scanPhotosWithAI;$("cancelScanButton").onclick=cancelScan;$("clearScanButton").onclick=clearScan;$("saveScanButton").onclick=saveScan;
$("aiBackendUrl").value=getAiUrl();$("saveAiSettingsButton").onclick=()=>{const v=$("aiBackendUrl").value.trim().replace(/\/$/,"");localStorage.setItem(AI_URL_KEY,v);$("aiSettingsStatus").textContent=v?"AI address saved.":"AI address cleared."};$("testAiButton").onclick=async()=>{const u=$("aiBackendUrl").value.trim().replace(/\/$/,"");if(!u)return $("aiSettingsStatus").textContent="Enter the backend address first.";$("aiSettingsStatus").textContent="Testing…";try{const r=await fetch(u+"/health");if(!r.ok)throw 0;$("aiSettingsStatus").textContent="AI connection is ready."}catch{$("aiSettingsStatus").textContent="Could not connect to that address."}};
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
